name: Build and Release

on:
  push:
    tags:
      - 'v*'  # solo se ejecuta al hacer push de un tag como v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'  # o la versión que uses

      - name: Construir el .jar
        run: mvn clean package -DskipTests

      - name: Crear release y subir artefacto
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            🚀 Nueva versión publicada automáticamente.

            ✅ Cambios:
            - Detalles a completar manualmente o desde changelog.md
          files: target/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
